config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :pages
  root 'pages#default_page'
  get '/contacto' => 'contact#index', as: 'contact'
  post '/contacto' => 'contact#deliver', as: 'send_message'
  get '/nuestro_trabajo' => 'albums#work', as: 'our_work'
  get '/album/:id' => 'albums#show', as: 'album'
  get '/admin' => 'admin#index', as: 'admin'

  get 'sort_pages' => 'pages#sort', as: 'sort_pages'
  post 'sort_pages' => 'pages#apply_sort', as: 'apply_sort'
end

app/views/partials/_contact.html.erb
<div class="contactfoot">
  <a href="tel:+541120759137">Tel: (011) 2075-9137</a>
  <span>| </span>
  <a href="mailto:info@yeahespacio.com.ar">E-mail: info@yeahespacio.com.ar</a>
</div>

app/views/partials/_flashes.html.erb
<%= "<p class=\"alert notice\">#{notice}</p>".html_safe if notice %>
<%= "<p class=\"alert error\">#{error}</p>".html_safe if error %>

app/views/partials/_javascripts.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_include_tag('admin', 'data-turbolinks-track' => true) if current_user %>

<script>
  var _gaq=[['_setAccount',"<%= ENV['YEAH_ANALYTICS_ID'] %>"],['_trackPageview']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g,s)}(document,'script'));
</script>

<%= content_for :post_js %>

app/views/partials/_jquery.html.erb
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="<%=asset_path('jquery-1.11.1.min.js')%>"><\/script>')</script>

app/views/partials/_menu.html.erb
<header>
  <div class="container">
    <div class="col-1-2">
      <h1 class="hide-text">
        <%= link_to image_tag('logoyeah.png'), root_path %>
      </h1>
    </div>
    <div class="col-1-2">
      <div class="chain"></div>
      <nav>
        <%= render 'admin/partials/menu' if current_user %>
        <%= menu_link 'nuestro trabajo', our_work_path %>
        <% @pages.each do |page| %>
          <%= menu_link(page.title, page) %>
        <% end %>
      </nav>
      <div class="chain"></div>
    </div>
  </div>
</header>

app/views/partials/_social.html.erb
<div class="social">
  <ul>
    <% social_links.each do |link| %>
      <li>
        <a href="<%= link.url %>">
          <i class="icon-<%= link.network %>"></i>
        </a>
      </li>
    <% end %>
  </ul>
</div>