config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :pages
  root 'pages#default_page'
  get '/contacto' => 'contact#index', as: 'contact'
  post '/contacto' => 'contact#deliver', as: 'send_message'
  get '/nuestro_trabajo' => 'albums#work', as: 'our_work'
  get '/album/:id' => 'albums#show', as: 'album'
  get '/admin' => 'admin#index', as: 'admin'

  get 'sort_pages' => 'pages#sort', as: 'sort_pages'
  post 'sort_pages' => 'pages#apply_sort', as: 'apply_sort'
end

app/views/pages/_form.html.erb
<%= simple_form_for(@page) do |f| %>
  <%= f.error_notification %>
  <%= f.input :title, label: 'titulo' %><br>
  <%= f.input :active, label: 'activa' %>
  <%= f.input :body, as: :ckeditor, label: 'cuerpo' %>
  <%= f.submit (@page.new_record? ? 'Crear Pagina' : 'Actualizar Pagina') %>
<% end %>

app/views/pages/edit.html.erb
<h1>Editando Pagina '<%= @page.title %>'</h1>

<%= render 'form' %>

<%= show_link @page %>
<%= back_link pages_path %>

app/views/pages/index.html.erb
<div class="page-content admin-editable pages">
  <%= form_tag sort_pages_path, id: 'js-sortable-container' %>
    <% @pages.each_with_index do |page, index|%>
      <p class="sort-page <%= !page.active || page.home_page? ? 'js-sort-disabled' : '' %>">
        <span class='hidden'> <%= "#{index + 1} - " %></span>
        <%= page.title.capitalize %>
        <span class='actions'><%= show_link(page) %></span>
        <span class='actions'><%= edit_link(page) %></span>
        <span class="actions"><%= destroy_link(page) %></span>
        <input type="hidden" value="<%= page.id %>" name="pages[]">
      </p>
    <% end %>
    <div class="actions">
      <%= link_to 'Ordenar', '#', id: 'sort-pages', class: 'button' %>
      <input type="submit" value="guardar" class="hidden button">
      <%= link_to 'cancelar', pages_path, class: 'hidden button' %>
    </div>
  </form>
</div>

app/views/pages/new.html.erb
<h1>Nueva Pagina</h1>

<%= render 'form' %>

<%= link_to 'Volver', pages_path %>

app/views/pages/show.html.erb
<div class="page-content admin-editable">

  <h1 class="title">
    <%= @page.title unless @page.slug == 'home' %> 
  </h1>
  <div><%= @page.body.html_safe %></div>

  <% if current_user %>
  <div class="actions">
    <%= edit_link(@page) %>
    <%= destroy_link(@page) %>
  </div>
  <% end %>
</div>