config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :pages
  root 'pages#default_page'
  get '/contacto' => 'contact#index', as: 'contact'
  post '/contacto' => 'contact#deliver', as: 'send_message'
  get '/nuestro_trabajo' => 'albums#work', as: 'our_work'
  get '/album/:id' => 'albums#show', as: 'album'
  get '/admin' => 'admin#index', as: 'admin'

  get 'sort_pages' => 'pages#sort', as: 'sort_pages'
  post 'sort_pages' => 'pages#apply_sort', as: 'apply_sort'
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end

  def deliver
    begin
      configure_pony
      Pony.mail(
        from: "#{contact_params['name']}<#{contact_params['mail']}>",
        to: ENV['YEAH_ADMIN_MAIL'],
        headers: { 'Content-Type' => 'text/html' },
        subject: "#{contact_params['last-name']}, #{contact_params['name']} le mando un mail desde YeahEspacio.com.ar",
        body: message_body
      )
      flash[:notice] = 'Mensaje enviado correctamente.'
    rescue
      flash[:error] = 'Ocurrio un problema enviando su mail, por favor intente nuevamente mas tarde.'
    end
    render 'thanks'
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :'last-name', :message, :mail)
  end

  def configure_pony
    Pony.options = {
      via: :smtp,
      via_options: {
        address: 'smtp.gmail.com',
        port: '587',
        user_name: ENV['YEAH_ADMIN_MAIL'],
        password: ENV['YEAH_MAIL_PASS'],
        authentication: :plain,
        enable_starttls_auto: true,
        domain: ENV['HOST']}
    }
  end

  def message_body
    "<html lang='en'><head> <meta charset='UTF-8'>
    <title>YeahEspacio!</title>
  </head> <body>
    <h1>#{contact_params['last-name']}, #{contact_params['name']}le mando un mail desde su pagina:</h1>
    <p> <span>Mensaje: </span> #{contact_params['message']}</p>
    <p> E-mail:
      <a href='mailto:#{contact_params['mail']}'>#{contact_params['mail']}</a>
    </p>
</body></html>"
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/index.html.erb
<%= form_tag(send_message_path) %>
  <div class="contact-row">
    <div class="left">
      <label for="name">nombre</label>
    </div>
    <div class="right">
      <input id="name" type="text" autofocus="true" required="true" name="contact[name]">
    </div>
  </div>

  <div class="contact-row">
    <div class="left">
      <label for="last-name">apellido</label>
    </div>
    <div class="right">
      <input id="last-name" type="text" required="true" name="contact[last-name]">
    </div>
  </div>

  <div class="contact-row">
    <div class="left">
      <label for="mail">e-mail</label>
    </div>
    <div class="right">
      <input id="mail" type="text" required="true" name="contact[mail]">
    </div>
  </div>

  <div class="contact-row">
    <div class="left">
      <label for="message">mensaje</label>
    </div>
    <div class="right">
      <textarea id="message" type="text" required="true" name="contact[message]" placeholder="Escriba su mensaje aqui..."/>
        </textarea>
    </div>
  </div>

  <input type="submit" value="enviar">
</form>

<%= render partial: 'partials/contact' %>

app/views/contact/thanks.html.erb
<h2> Gracias por comunicarse. </h2>